// user
export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const REQUEST_USER_INFO_FAIL = 'REQUEST_USER_INFO_FAIL';

// images
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const REQUEST_MORE = 'REQUEST_MORE';
export const RECEIVE_MORE = 'RECEIVE_MORE';

